FROM python:3.9-slim as base

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    gcc \
    libc-dev \
    libpq-dev \
    python3-dev

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the frontend directory to /app/frontend
COPY ./frontend /app/frontend

# Set the working directory to /app, which will be in PYTHONPATH
WORKDIR /app

EXPOSE 5679

###########START NEW IMAGE : DEBUGGER ###################
FROM base as debug
RUN pip install debugpy

CMD python -m debugpy --listen 0.0.0.0:5679 --wait-for-client -m frontend.ui_kit.app

###########START NEW IMAGE: PRODUCTION ###################
FROM base as prod

CMD ["python", "-m", "frontend.ui_kit.app"]